build.doc.topics <- function(doc_attrs, model, threshold = 0.00001)
{
  # TODO make attrs a doc attribute structure
  # See http://stackoverflow.com/questions/17046336/here-we-go-again-append-an-element-to-a-list-in-r
  
  ct <- 0
  docs <- list()
  length(docs) <- model$D
  
  for (ix in 1 : model$D)
  {
    d <- list()
    d$id <- ix
    d$title <- doc_attrs[ix, 4]  # Baysinger Keim Zeithaml - An Empirical Evaluation.txt
    
    d$attrs <- list()
    d$attrs$volume <- doc_attrs[ix,2]  # Volume 28
    d$attrs$issue <- doc_attrs[ix,3]   # Issue 1 - March 1985
    d$attrs$path <- doc_attrs[ix, 1]   # Volume 28/Issue 1 - March 1985/Baysinger Keim Zeithaml - An Empirical Evaluation.txt
    
    d$topics <- which(model$docAssignments[ix, ] > threshold)
    d$topic_ratios <- model$docAssignments[ix, d$topics]
    
    ct <- ct + 1
    docs[[ct]] <- d
  }
  
  return(docs)
}


# RETURN
# -- id
# -- title
# -- top_words
#    -- words
#    -- weights
# -- docs
#    -- ids
#    -- weights
# -- wordcloud
#
#
build.topic.words <- function(model, num.words = 100)
{
  ct <- 0
  topics <- list()
  length(topics) <- model$K
  
  vocabulary <- colnames(model$topics)
  for (ix in 1 : model$K)
  {
    # the words mostl likely to be generated by this topic
    sortedTopics <- sort.int(model$topics[ix,], decreasing=T, index.return=T)
    sortedTopics <- sortedTopics$ix[1:num.words]
    top_words <- list() 
    top_words$words <- vocabulary[sortedTopics]
    top_words$weights <- model$topics[ix, sortedTopics]

    ct <- ct + 1
    topics[[ix]] <- top_words
  }
  
  return(topics)
}

build.topic.docs <- function(model, assignments, num.words = 100, generate_wordcloud=T)
{
  ct <- 0
  topics <- list()
  length(topics) <- model$K
  
  for (ix in 1 : model$K)
  {
    topic <- list()
    topic$id <- ix
    
    # documents associated with this topic
    sorted_docs <- sort.int(assignments[, ix], decreasing=T, index.return=T)
    sorted_docs <- sorted_docs$ix[which(sorted_docs$x > 0.01)]
    topic$docs <- list()
    topic$docs$ids <- sorted_docs
    topic$docs$weights <- assignments[sorted_docs, ix]
    
    ct <- ct + 1
    topics[[ct]] <- topic
  }
  
  return(topics)
}

build.topic.clouds <- function(top_words)
{
  result <- NULL
  for (ix in 1 : model$K)
  {
    filename <- paste("plots/Topic ", ix, ".png")
    png(filename, width=12, height=8, units="in", res=300)
    wordcloud(top_words$words,
              top_words$weights,
              scale=c(4, .2),
              rot.per=0.1,
              random.order=FALSE,
              colors=brewer.pal(8, "Dark2"))
    dev.off()
    
    result <- c(result, filename)    
  }
  
  return(result)
}

#topic_topdocs <- build.topic.docs(model$docAssignments)
#fconn <- file("docs.json")
#writeLines(toJSON(topic_topdocs, auto_unbox=T, pretty=T), fconn)
#close(fconn)